### ISSUE TITLE
sbt.ResolveException: unresolved dependency: com.typesafe.akka#akka-actor;2.0.1: not found

### ISSUE THREAD

**Issue by taot** [spray/twirl#14]
I'm trying to build the example in Arch Linux, and I have sbt 0.12.0

I've tried with tags v0.6.0, v0.6.1, and master, all having the same issue when I launch sbt in the example directory:

sbt.ResolveException: unresolved dependency: com.typesafe.akka#akka-actor;2.0.1: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:214)
        at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
        at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:102)
        at sbt.IvySbt.liftedTree1$1(Ivy.scala:49)
        at sbt.IvySbt.action$1(Ivy.scala:49)
        at sbt.IvySbt$$anon$3.call(Ivy.scala:58)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:75)
        at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:79)
        at xsbt.boot.Using$.withResource(Using.scala:11)
        at xsbt.boot.Using$.apply(Using.scala:10)
        at xsbt.boot.Locks$GlobalLock.liftedTree1$1(Locks.scala:51)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:51)
        at xsbt.boot.Locks$.apply0(Locks.scala:30)
        at xsbt.boot.Locks$.apply(Locks.scala:27)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:58)

It seems akka-actor-2.0.1 is quite old, and couldn't be found in maven repo.

Is there a specific way of building the example that I don't know of?

**Comment by jrudolph** [comment]
The example still used version 0.6.0 of twirl which suffered from #5. I updated current master to use twirl 0.6.1 in the example. Thanks for catching this.

**Comment by taot** [comment]
Thanks a lot for the quick response! It's working now!
